### ISSUE TITLE
Hived status returns error

### ISSUE THREAD

**Issue by matis11** [bbc/hive-runner-android#42]
Hello!
I was trying to setup hive-runner-android on my local machine, unfortunately I am still getting error listed below.

```
WARN: Unresolved specs during Gem::Specification.reset:
      json (>= 1.7.7, ~> 1.0, ~> 1.7, ~> 1.8)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/home/mateusz/.rvm/gems/ruby-2.2.3/gems/hive-runner-2.0.3/bin/hived:12:in `require': cannot load such file -- daemons (LoadError)
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/hive-runner-2.0.3/bin/hived:12:in `<top (required)>'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/bin/hived:23:in `load'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/bin/hived:23:in `<main>'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

Could you please provide me any support?

Cheers!

**Comment by jrmhaig** [comment]
Hi.

I think that the warning about json is not a problem. The problem is that it is unable to load the daemons gem. Can you please paste the output of

```
bundle list daemons
```

Also, can you have a look in `log/hive.log` and `log/hived.log` to see if there are any errors there.

**Comment by matis11** [comment]
After updating my bundler I was able to finish the setup, thank you.

Right now, when I try to start hived using _hived run_, I am getting this error:
```
hived run

start_hive: process with pid 4164 started.
*** Starting Hive at 2015-12-10 11:16:03 +0100 ***
NOTE: Dependency.new w/ a regexp is deprecated.
Dependency.new called from /home/mateusz/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:907
/home/mateusz/.rvm/gems/ruby-2.2.3/gems/macaddr-1.7.1/lib/macaddr.rb:86:in `block in from_getifaddrs': undefined method `pfamily' for nil:NilClass (NoMethodError)
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/macaddr-1.7.1/lib/macaddr.rb:85:in `select'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/macaddr-1.7.1/lib/macaddr.rb:85:in `from_getifaddrs'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/macaddr-1.7.1/lib/macaddr.rb:62:in `address'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/hive-runner-2.0.3/lib/hive.rb:157:in `mac_address'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/hive-runner-2.0.3/lib/hive.rb:96:in `id'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/bundler/gems/hive-runner-android-764db125667b/lib/hive/controller/android.rb:83:in `detect'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/hive-runner-2.0.3/lib/hive/register.rb:60:in `block in check_controllers'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/hive-runner-2.0.3/lib/hive/register.rb:55:in `each'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/hive-runner-2.0.3/lib/hive/register.rb:55:in `check_controllers'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/hive-runner-2.0.3/lib/hive/register.rb:39:in `instantiate_controllers'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/hive-runner-2.0.3/bin/start_hive:115:in `<top (required)>'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons/application.rb:218:in `load'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons/application.rb:218:in `start_load'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons/application.rb:297:in `start'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons/controller.rb:59:in `run'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons.rb:144:in `block in run'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons/cmdline.rb:88:in `call'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons/cmdline.rb:88:in `catch_exceptions'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons.rb:143:in `run'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/hive-runner-2.0.3/bin/hived:31:in `<top (required)>'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/bin/hived:23:in `load'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/bin/hived:23:in `<main>'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
mateusz@intern-lap:~/Dev/my_hive$ hived run
start_hive: process with pid 4164 started.
*** Starting Hive at 2015-12-10 11:16:03 +0100 ***
NOTE: Dependency.new w/ a regexp is deprecated.
Dependency.new called from /home/mateusz/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:907
/home/mateusz/.rvm/gems/ruby-2.2.3/gems/macaddr-1.7.1/lib/macaddr.rb:86:in `block in from_getifaddrs': undefined method `pfamily' for nil:NilClass (NoMethodError)
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/macaddr-1.7.1/lib/macaddr.rb:85:in `select'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/macaddr-1.7.1/lib/macaddr.rb:85:in `from_getifaddrs'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/macaddr-1.7.1/lib/macaddr.rb:62:in `address'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/hive-runner-2.0.3/lib/hive.rb:157:in `mac_address'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/hive-runner-2.0.3/lib/hive.rb:96:in `id'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/bundler/gems/hive-runner-android-764db125667b/lib/hive/controller/android.rb:83:in `detect'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/hive-runner-2.0.3/lib/hive/register.rb:60:in `block in check_controllers'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/hive-runner-2.0.3/lib/hive/register.rb:55:in `each'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/hive-runner-2.0.3/lib/hive/register.rb:55:in `check_controllers'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/hive-runner-2.0.3/lib/hive/register.rb:39:in `instantiate_controllers'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/hive-runner-2.0.3/bin/start_hive:115:in `<top (required)>'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons/application.rb:218:in `load'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons/application.rb:218:in `start_load'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons/application.rb:297:in `start'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons/controller.rb:59:in `run'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons.rb:144:in `block in run'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons/cmdline.rb:88:in `call'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons/cmdline.rb:88:in `catch_exceptions'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/daemons-1.2.3/lib/daemons.rb:143:in `run'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/gems/hive-runner-2.0.3/bin/hived:31:in `<top (required)>'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/bin/hived:23:in `load'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/bin/hived:23:in `<main>'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/mateusz/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by matis11** [comment]
This error was caused by my VPN, disabling VPN fixed the problem.

Thank you for your support!

**Comment by matis11** [comment]
More info @ https://github.com/ahoward/macaddr/pull/25/files
