### ISSUE TITLE
Periodic crashes

### ISSUE THREAD

**Issue by jonpwilson** [bbc/hive-runner-android#54]
Keep getting another adb error taking out the whole hive: 

```
Unrecognised exception whilst finding device '0bccd1b9' (state: device)
error: device '0bccd1b9' not found
["/home/hive/.rvm/gems/ruby-2.3.0/gems/device_api-android-1.2.7/lib/device_api/android/adb.rb:260:in `shell'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/device_api-android-1.2.7/lib/device_api/android/adb.rb:41:in `getprop'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/device_api-android-1.2.7/lib/device_api/android/device.rb:302:in `get_prop'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/device_api-android-1.2.7/lib/device_api/android/device.rb:69:in `manufacturer'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/device_api-android-1.2.7/lib/device_api/android.rb:40:in `get_device_type'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/device_api-android-1.2.7/lib/device_api/android.rb:22:in `block in devices'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/device_api-android-1.2.7/lib/device_api/android.rb:20:in `map'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/device_api-android-1.2.7/lib/device_api/android.rb:20:in `devices'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-android-1.1.6/lib/hive/controller/android.rb:102:in `detect_devicedb'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-android-1.1.6/lib/hive/controller/android.rb:11:in `detect'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.0.12/lib/hive/register.rb:60:in `block in check_controllers'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.0.12/lib/hive/register.rb:55:in `each'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.0.12/lib/hive/register.rb:55:in `check_controllers'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.0.12/lib/hive/register.rb:47:in `block in run'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.0.12/lib/hive/register.rb:44:in `loop'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.0.12/lib/hive/register.rb:44:in `run'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.0.12/bin/start_hive:120:in `<top (required)>'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons/application.rb:218:in `load'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons/application.rb:218:in `start_load'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons/application.rb:297:in `start'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons/controller.rb:56:in `run'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons.rb:144:in `block in run'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons/cmdline.rb:88:in `catch_exceptions'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons.rb:143:in `run'", "/home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.0.12/bin/hived:31:in `<top (required)>'", "/home/hive/.rvm/gems/ruby-2.3.0/bin/hived:23:in `load'", "/home/hive/.rvm/gems/ruby-2.3.0/bin/hived:23:in `<main>'", "/home/hive/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'", "/home/hive/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'"]
/home/hive/.rvm/gems/ruby-2.3.0/gems/device_api-android-1.2.7/lib/device_api/android/adb.rb:260:in `shell': error: device '0bccd1b9' not found (DeviceAPI::Android::ADBCommandError)
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/device_api-android-1.2.7/lib/device_api/android/adb.rb:41:in `getprop'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/device_api-android-1.2.7/lib/device_api/android/device.rb:302:in `get_prop'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/device_api-android-1.2.7/lib/device_api/android/device.rb:63:in `model'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-android-1.1.6/lib/hive/controller/android.rb:162:in `block in detect_devicedb'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-android-1.1.6/lib/hive/controller/android.rb:156:in `map'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-android-1.1.6/lib/hive/controller/android.rb:156:in `detect_devicedb'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-android-1.1.6/lib/hive/controller/android.rb:11:in `detect'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.0.12/lib/hive/register.rb:60:in `block in check_controllers'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.0.12/lib/hive/register.rb:55:in `each'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.0.12/lib/hive/register.rb:55:in `check_controllers'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.0.12/lib/hive/register.rb:47:in `block in run'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.0.12/lib/hive/register.rb:44:in `loop'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.0.12/lib/hive/register.rb:44:in `run'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.0.12/bin/start_hive:120:in `<top (required)>'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons/application.rb:218:in `load'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons/application.rb:218:in `start_load'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons/application.rb:297:in `start'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons/controller.rb:56:in `run'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons.rb:144:in `block in run'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons/cmdline.rb:88:in `catch_exceptions'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons.rb:143:in `run'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.0.12/bin/hived:31:in `<top (required)>'
        from /home/hive/.rvm/gems/ruby-2.3.0/bin/hived:23:in `load'
        from /home/hive/.rvm/gems/ruby-2.3.0/bin/hived:23:in `<main>'
        from /home/hive/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /home/hive/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'`
```

**Comment by jonpwilson** [comment]
This looks like it should be fixed with the more recent version of Hive Runner Android as the `detect_devicedb` code has been removed
